"""initial migration

Revision ID: 090e0d2978fd
Revises: 
Create Date: 2020-12-28 20:44:04.062493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090e0d2978fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderdetails',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderNumber', sa.Integer(), nullable=False),
    sa.Column('productCode', sa.Integer(), nullable=False),
    sa.Column('quantityOrdered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('orderNumber', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('serverID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('orderNumber')
    )
    op.create_table('products',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('productCode', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=25), nullable=True),
    sa.Column('priceEach', sa.Float(), nullable=True),
    sa.Column('textDescription', sa.String(length=200), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('productCode')
    )
    op.create_table('users',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=True),
    sa.Column('serverID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('orderdetails')
    # ### end Alembic commands ###
