"""added resource mixin

Revision ID: 9eac5a034bad
Revises: d71623bf86a9
Create Date: 2020-12-13 12:47:11.042436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eac5a034bad'
down_revision = 'd71623bf86a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetails', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('orderdetails', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('products', 'updated_on')
    op.drop_column('products', 'created_on')
    op.drop_column('orders', 'updated_on')
    op.drop_column('orders', 'created_on')
    op.drop_column('orderdetails', 'updated_on')
    op.drop_column('orderdetails', 'created_on')
    # ### end Alembic commands ###
