"""init database

Revision ID: d71623bf86a9
Revises: 
Create Date: 2020-12-13 12:23:44.960446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71623bf86a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('productCode', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=25), nullable=True),
    sa.Column('priceEach', sa.Float(), nullable=True),
    sa.Column('textDescription', sa.String(length=200), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('productCode')
    )
    op.create_index(op.f('ix_products_productName'), 'products', ['productName'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('orderNumber', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('serverID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serverID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('orderNumber')
    )
    op.create_index(op.f('ix_orders_orderDate'), 'orders', ['orderDate'], unique=False)
    op.create_table('orderdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderNumber', sa.Integer(), nullable=False),
    sa.Column('productCode', sa.String(length=25), nullable=False),
    sa.Column('quantityOrdered', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderNumber'], ['orders.orderNumber'], ),
    sa.ForeignKeyConstraint(['productCode'], ['products.productCode'], ),
    sa.PrimaryKeyConstraint('id', 'orderNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderdetails')
    op.drop_index(op.f('ix_orders_orderDate'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_productName'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
